#!/bin/bash
# vim: et sr sw=4 ts=4 smartindent:
# create_aws_instance_info.sh
#
# Gets IMMUTABLE instance info from AWS metadata
# i.e. we're not interested in putting metadata or tag values in to the file
# that might change over time.
#
INFO_FILE=/etc/eurostar/aws_instance_info
TIMESTAMP="$(date +'%Y-%m-%d %H:%M:%S')"
AWS_DOC_URI=http://169.254.169.254/latest/dynamic/instance-identity/document
AWS_DOC=$(curl -s $AWS_DOC_URI)
if [[ -z $AWS_DOC ]]; then
    echo "$0 ERROR: couldn't fetch $AWS_DOC_URI with curl"
    exit 1
fi

cat << EOF >$INFO_FILE
# [$TIMESTAMP] AWS INSTANCE INFO GENERATED BY $0
AWS_INSTANCE_ID=$(   echo "$AWS_DOC" | grep '^[ ]\+"instanceId"'   | awk -F\" '{print $4}' )
AWS_INSTANCE_TYPE=$( echo "$AWS_DOC" | grep '^[ ]\+"instanceType"' | awk -F\" '{print $4}' )
AWS_REGION=$(        echo "$AWS_DOC" | grep '^[ ]\+"region"'       | awk -F\" '{print $4}' )
AWS_AZ=$( echo "$AWS_DOC" | grep '^[ ]\+"availabilityZone"' | awk -F\" '{print $4}' |
    sed -e 's/.*\(.\)$/\1/'
)
# END AWS INSTANCE INFO GENERATED BY $0
EOF

cat $INFO_FILE
