#!/bin/bash
# vim: et sr sw=4 ts=4 smartindent:
#
# create_eurostar_service_info.sh
#
# Will generate a file under /etc/eurostar/eurostar_service_info
# This file contains key=value pairs that can be sourced in to a 
# bash script etc ...
#
# It contains stuff that is useful to determine the name and type of this
# service amongst other things.
#
#
REQUIRED_VARS="
    EUROSTAR_SERVICE_NAME
    EUROSTAR_SERVICE_ROLE
    EUROSTAR_RELEASE_VERSION
"

INFO_FILE="/etc/eurostar/eurostar_service_info"
FAILED_VALIDATION=''
TIMESTAMP="$(date +'%Y-%m-%d %H:%M:%S')"
BUILD_INFO="$PACKER_BUILD_NAME $PACKER_BUILD_TYPE"
OUTPUT_STR="# [$TIMESTAMP] GENERATED BY PACKER: $BUILD_INFO"

function check_var_defined() {
    var_name="$1"
    var_val="${!var_name}"
    if [[ -z $var_val ]]; then
        echo "$0 ERROR: You must pass \$$var_name to this script" >&2
        FAILED_VALIDATION="you bet'cha"
        return 1
    fi

    if [[ $var_val =~ [^_a-zA-Z0-9] ]]; then
        echo "$0 ERROR: ILLEGAL CHAR in $var_name val: $var_valonly" >&2 
        echo "$0 ERROR: ... only use alphanumerics or underscore in the value"
        FAILED_VALIDATION="you bet'cha"
        return 1
    fi
}

function add_to_info_str() {
    var_name="$1"
    var_val="${!var_name}"
    key_val="$var_name=$var_val"
    OUTPUT_STR="$OUTPUT_STR\n$key_val"
}

for this_var in $REQUIRED_VARS; do
    check_var_defined $this_var \
    && add_to_info_str $this_var
done

if [[ ! -z $FAILED_VALIDATION ]]; then
    echo "$0 EXIT: FAILURE. One of more required vars not passed to this script."
    exit 1
fi

OUTPUT_STR="$OUTPUT_STRING\n# END GENERATED BY PACKER\n"

mkdir -p $(dirname $INFO_FILE) 2>/dev/null
echo "$OUTPUT_STR" >$INFO_FILE

